[versions]
# project-level dependency
android-gradle = "8.7.2"
kotlin = '2.0.21'
ksp = '2.0.21-1.0.27'
hilt = '2.52'
google-services = '4.4.2'
firebase-gradle = '3.0.2'
oss-licenses-version = '0.10.6'
compileSdk = "34"
targetSdk = "34"
minSdk = "24"
# Update appVersion, versionCode both
appVersion = "2.1.3"
versionCode = "20103"

# app-level dependency
# Kotlin
kotlinx-coroutines = '1.9.0'
kotlinx-serialization-json = "1.7.3"

# Compose
compose-compiler = '1.4.8'
compose-bom = '2024.10.01'

# Androidx
androidx-lifecycle = '2.8.7'
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.2.0"
androidx-constraintlayout-compose = "1.1.0"
androidx-activity = '1.9.3'
androidx-core = "1.13.1"
androidx-fragment = '1.8.5'
androidx-paging = '3.3.2'
androidx-room = '2.6.1'
androidx-viewpager2 = '1.1.0'
androidx-work = '2.9.1'
androidx-navigation = "2.8.3"
androidx-startup = '1.2.0'
androidx-swiperefreshlayout = '1.2.0-alpha01'
android-material = '1.12.0'
androidx-hilt = "1.2.0"
androidx-test-core = "1.6.1"
androidx-test-rules = "1.6.1"
androidx-test = "1.6.2"
desugarJdk = "2.1.2"

# Test
androidx-espresso = "3.6.1"

# Third Party
coil = '2.7.0'
okhttp = '4.12.0'
retrofit = '2.11.0'
firebase = '33.5.1'
crashlytics = "3.0.2"
lottie = "6.6.0"
ktor = "3.0.1"

[libraries]
# Project-level dependencies
android-gradle = { module = 'com.android.tools.build:gradle', version.ref = 'android-gradle' }
kotlin-gradle = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin' }
hilt-android-gradle = { module = 'com.google.dagger:hilt-android-gradle-plugin', version.ref = 'hilt' }
google-services = { module = 'com.google.gms:google-services', version.ref = 'google-services' }
firebase-crashlytics-gradle = { module = 'com.google.firebase:firebase-crashlytics-gradle', version.ref = 'firebase-gradle' }
oss-licenses = { module = 'com.google.android.gms:oss-licenses-plugin', version.ref = 'oss-licenses-version' }
kotlinx-serialization-plugin = { module = 'org.jetbrains.kotlin:kotlin-serialization', version.ref = 'kotlin' }

# Kotlin
kotlinx-coroutines-android = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-android', version.ref = 'kotlinx-coroutines' }
kotlinx-coroutines-core = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-core', version.ref = 'kotlinx-coroutines' }
kotlinx-coroutines-reactive = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-reactive', version.ref = 'kotlinx-coroutines' }
# Test는 bundle로 묶지 말기 (필요한 모듈에서만 별도로 선언)
kotlinx-coroutines-test = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-test', version.ref = 'kotlinx-coroutines' }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

# Android
android-material = { module = 'com.google.android.material:material', version.ref = 'android-material' }

# Compose
compose-bom = { module = 'androidx.compose:compose-bom', version.ref = 'compose-bom' }
compose-foundation = { module = 'androidx.compose.foundation:foundation' }
compose-material = { module = 'androidx.compose.material:material' }
compose-material3 = { module = 'androidx.compose.material3:material3' }
compose-material-icons-core = { module = 'androidx.compose.material:material-icons-core' }
compose-material-icons-extended = { module = 'androidx.compose.material:material-icons-extended' }
compose-ui = { module = 'androidx.compose.ui:ui' }
compose-ui-test = { module = 'androidx.compose.ui:ui-test' }
compose-ui-test-junit4 = { module = 'androidx.compose.ui:ui-test-junit4' }
compose-ui-test-manifest = { module = 'androidx.compose.ui:ui-test-manifest' }
compose-ui-tooling = { module = 'androidx.compose.ui:ui-tooling' }
compose-ui-tooling-preview = { module = 'androidx.compose.ui:ui-tooling-preview' }
compose-compiler-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

# AndroidX
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { module = 'androidx.core:core-ktx', version.ref = 'androidx-core' }
androidx-startup-runtime = { module = 'androidx.startup:startup-runtime', version.ref = 'androidx-startup' }
androidx-swiperefreshlayout = { module = 'androidx.swiperefreshlayout:swiperefreshlayout', version.ref = 'androidx-swiperefreshlayout' }
androidx-viewpager2 = { module = 'androidx.viewpager2:viewpager2', version.ref = 'androidx-viewpager2' }
androidx-lifecycle-viewmodel-ktx = { module = 'androidx.lifecycle:lifecycle-viewmodel-ktx', version.ref = 'androidx-lifecycle' }
androidx-lifecycle-livedata = { module = 'androidx.lifecycle:lifecycle-livedata', version.ref = 'androidx-lifecycle' }
androidx-activity-ktx = { module = 'androidx.activity:activity-ktx', version.ref = 'androidx-activity' }
androidx-fragment-ktx = { module = 'androidx.fragment:fragment-ktx', version.ref = 'androidx-fragment' }
androidx-activity-compose = { module = 'androidx.activity:activity-compose', version.ref = 'androidx-activity' }
androidx-constraintlayout-compose = { module = 'androidx.constraintlayout:constraintlayout-compose', version.ref = 'androidx-constraintlayout-compose' }
androidx-lifecycle-viewmodel-compose = { module = 'androidx.lifecycle:lifecycle-viewmodel-compose', version.ref = 'androidx-lifecycle' }
androidx-lifecycle-runtime-compose = { module = 'androidx.lifecycle:lifecycle-runtime-compose', version.ref = 'androidx-lifecycle' }
androidx-paging-compose = { module = 'androidx.paging:paging-compose', version.ref = 'androidx-paging' }
hilt-navigation-compose = { module = 'androidx.hilt:hilt-navigation-compose', version.ref = 'androidx-hilt' }
androidx-navigation-compose = { module = 'androidx.navigation:navigation-compose', version.ref = 'androidx-navigation' }
desugarLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdk" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
androidx-paging-common-ktx = { module = 'androidx.paging:paging-common-ktx', version.ref = 'androidx-paging' }
androidx-paging-runtime-ktx = { module = 'androidx.paging:paging-runtime-ktx', version.ref = 'androidx-paging' }
androidx-room-ktx = { module = 'androidx.room:room-ktx', version.ref = 'androidx-room' }
androidx-room-runtime = { module = 'androidx.room:room-runtime', version.ref = 'androidx-room' }
androidx-room-compiler = { module = 'androidx.room:room-compiler', version.ref = 'androidx-room' }
androidx-room-paging = { module = 'androidx.room:room-paging', version.ref = 'androidx-room' }
androidx-work-runtime-ktx = { module = 'androidx.work:work-runtime-ktx', version.ref = 'androidx-work' }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }

# Unit Test
mockito-core = 'org.mockito:mockito-core:5.14.2'
mockito-inline = 'org.mockito:mockito-inline:5.2.0'
mockito-kotlin = 'org.mockito.kotlin:mockito-kotlin:5.4.0'
junit = 'junit:junit:4.13.2'
robolectric = 'org.robolectric:robolectric:4.13'

# Android Test
androidx-core-testing = 'androidx.arch.core:core-testing:2.2.0'
androidx-test-core = { module = 'androidx.test:core', version.ref = 'androidx-test-core' }
androidx-fragment-testing = { module = 'androidx.fragment:fragment-testing', version.ref = 'androidx-fragment' }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidx-navigation" }
androidx-work-testing = { module = 'androidx.work:work-testing', version.ref = 'androidx-work' }
androidx-room-testing = { module = 'androidx.room:room-testing', version.ref = 'androidx-room' }
hilt-android-testing = { module = 'com.google.dagger:hilt-android-testing', version.ref = 'hilt' }
androidx-espresso-core = { module = 'androidx.test.espresso:espresso-core', version.ref = 'androidx-espresso' }
androidx-espresso-intents = { module = 'androidx.test.espresso:espresso-intents', version.ref = 'androidx-espresso' }
androidx-junit = 'androidx.test.ext:junit:1.2.1'
mockito-android = 'org.mockito:mockito-android:5.14.2'
androidx-test-runner = { module = 'androidx.test:runner', version.ref = 'androidx-test' }
androidx-test-rules = { module = 'androidx.test:rules', version.ref = 'androidx-test-rules' }

# Firebase
firebase-bom = { module = 'com.google.firebase:firebase-bom', version.ref = 'firebase' }
firebase-messaging-ktx = { module = 'com.google.firebase:firebase-messaging' }
firebase-analytics-ktx = { module = 'com.google.firebase:firebase-analytics' }
firebase-crashlytics-ktx = { module = 'com.google.firebase:firebase-crashlytics' }

# Lottie
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

# Coil
coil = { module = 'io.coil-kt:coil', version.ref = 'coil' }
coil-gif = { module = 'io.coil-kt:coil-gif', version.ref = 'coil' }
coil-compose = { module = 'io.coil-kt:coil-compose', version.ref = 'coil' }

# Hilt
hilt-android = { module = 'com.google.dagger:hilt-android', version.ref = 'hilt' }
hilt-compiler = { module = 'com.google.dagger:hilt-compiler', version.ref = 'hilt' }

# OkHttp
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = 'com.squareup.okhttp3:okhttp' }
okhttp-logging-interceptor = { module = 'com.squareup.okhttp3:logging-interceptor' }
okhttp-mockwebserver = { module = 'com.squareup.okhttp3:mockwebserver' }

# Play Services
play-services-oss-licenses = 'com.google.android.gms:play-services-oss-licenses:17.1.0'
play-services-auth = 'com.google.android.gms:play-services-auth:21.2.0'

# Retrofit
retrofit-bom = { module = 'com.squareup.retrofit2:retrofit-bom', version.ref = 'retrofit' }
retrofit = { module = 'com.squareup.retrofit2:retrofit' }
retrofit-converter-gson = { module = 'com.squareup.retrofit2:converter-gson' }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Other libraries
keyboardvisibilityevent = 'net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent:3.0.0-RC3'
leakcanary-android = 'com.squareup.leakcanary:leakcanary-android:2.14'
pageindicatorview = 'com.romandanylyk:pageindicatorview:1.0.3'
shimmer = 'com.facebook.shimmer:shimmer:0.5.0'
timber = 'com.jakewharton.timber:timber:5.0.1'
semver = "net.swiftzer.semver:semver:2.0.0"

[bundles]
retrofit = [
    'retrofit',
    'retrofit-converter-gson',
]
compose = [
    'compose-foundation',
    'compose-material',
    'compose-material-icons-core',
    'compose-material-icons-extended',
    'compose-ui',
    'compose-ui-test',
    'compose-ui-test-junit4',
    'compose-ui-test-manifest',
    'compose-ui-tooling',
    'compose-ui-tooling-preview',
    'androidx-navigation-compose',
]
compose-interop = [
    'androidx-activity-compose',
    'hilt-navigation-compose',
    'androidx-lifecycle-viewmodel-compose',
    'androidx-paging-compose',
    'androidx-constraintlayout-compose',
    'lottie-compose',
    'androidx-lifecycle-runtime-compose',
]
coil = [
    'coil',
    'coil-gif',
    'coil-compose'
]
coroutines = [
    'kotlinx-coroutines-android',
    'kotlinx-coroutines-core',
    'kotlinx-coroutines-reactive',
]
firebase = [
    'firebase-analytics-ktx',
    'firebase-messaging-ktx',
    'firebase-crashlytics-ktx',
]
paging = [
    'androidx-paging-runtime-ktx',
    'androidx-paging-common-ktx',
]
viewmodel-ktx = [
    'androidx-lifecycle-viewmodel-ktx',
    'androidx-activity-ktx',
]
androidx-work = [
    'androidx-work-runtime-ktx',
    'androidx-hilt-work',
]
unit-test = [
    'mockito-core',
    'mockito-inline',
    'mockito-kotlin',
    'junit',
    'androidx-core-testing',
    'androidx-test-core',
    'robolectric',
]
android-test = [
    'mockito-android',
    'androidx-junit',
    'androidx-espresso-core',
    'androidx-test-runner',
    'androidx-test-rules'
]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
